<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => '',
    'Already have account ?' => '',
    'Are you sure you want to delete this item?' => '',
    'Are you sure you want to delete this post?' => '',
    'Author' => '',
    'Blog name' => '',
    'Blog subtitle' => '',
    'Contact' => '',
    'Content' => '',
    'Copyright &copy; {year}' => '',
    'Create Post' => '',
    'Create User' => '',
    'Create new account' => '',
    'Created At' => '',
    'Created By' => '',
    'Delete' => '',
    'Deleted by user' => '',
    'Draft' => '',
    'Edit as markdown' => '',
    'Go home' => '',
    'Home' => '',
    'ID' => '',
    'Image' => '',
    'Login' => '',
    'Login / Register' => '',
    'Logout' => '',
    'Manage posts' => '',
    'Menu' => '',
    'Newer Posts' => '',
    'Older Posts' => '',
    'Posts' => '',
    'Published' => '',
    'Published Time' => '',
    'Register' => '',
    'Save' => '',
    'Slug' => '',
    'Summary' => '',
    'The post not found' => '',
    'The post was not published.' => '',
    'The post was published.' => '',
    'The post was unpublished.' => '',
    'The requested page does not exist.' => '',
    'This post was not published.' => '',
    'Thumbnail' => '',
    'Title' => '',
    'Unpublished by Admin' => '',
    'Update' => '',
    'Update User: mode' => '',
    'Update now' => '',
    'Updated At' => '',
    'Updated By' => '',
    'Users' => '',
    'You do not have permissions to do this action.' => '',
    'You do not have permissions to execute this action' => '',
    '[Publish]' => '',
    '[Unpublish]' => '',
    'in {0} minutes' => '',
];
